export { Hero }             from './Hero';
export { MarqueeStrip }     from './MarqueeStrip';
export { WhyChooseUs }      from './WhyChooseUs';
export { HowItWorks }       from './HowItWorks';
export { WhyNow }           from './WhyNow';
export { AboutUs }          from './AboutUs';
export { TestimonialMarquee } from './TestimonialMarquee';
export { CtaBanner }        from './CtaBanner';
export { Faq }              from './Faq';
